spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: IES_DEV
    password: IES_DEV
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
